# Generated by Django 6.0.4 on 2026-05-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(db_index=True, help_text='Discipline code, e.g. fall_8ball, summer_scotch_doubles.', max_length=64)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'ordering': ['-start_date', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_week_number', models.PositiveIntegerField(default=1, help_text='First week this team participates (1-based within the season).')),
                ('last_week_number', models.PositiveIntegerField(blank=True, help_text='Last participating week; blank means through final week.', null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_teams', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_teams', to='league.team')),
            ],
            options={
                'ordering': ['season', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Round index (1-based) within the season.')),
                ('calendar_date', models.DateField(blank=True, help_text='Primary league session date (typically Thursday).', null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='league.season')),
            ],
            options={
                'ordering': ['season', 'number'],
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField(blank=True, help_text='Table 1–5 when assigned.', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], db_index=True, default='scheduled', max_length=20)),
                ('counts_as_round', models.PositiveIntegerField(blank=True, help_text="Standings / rotation round this result counts toward when it differs from week.number (e.g. a pairing scored as round 14 but anchored to round 13's calendar week).", null=True)),
                ('played_on', models.DateField(blank=True, help_text='Actual calendar date of play; blank means primary session night.', null=True)),
                ('session_kind', models.CharField(choices=[('primary_thursday', 'Primary league night (Thursday)'), ('makeup_same_week', 'Make-up: same calendar week, non-Thursday (by agreement)')], db_index=True, default='primary_thursday', max_length=24)),
                ('away_season_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='league.seasonteam')),
                ('home_season_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='league.seasonteam')),
                ('week', models.ForeignKey(help_text='Round row whose calendar week anchors this match (primary Thursday night).', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.week')),
            ],
            options={
                'ordering': ['week', 'home_season_team_id'],
            },
        ),
        migrations.CreateModel(
            name='ByeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_points_awarded', models.PositiveSmallIntegerField(default=3, help_text='League team points for this bye; override when rules differ.')),
                ('season_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bye_assignments', to='league.seasonteam')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bye_assignments', to='league.week')),
            ],
            options={
                'ordering': ['week', 'season_team_id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Inclusive end date; blank means still active.', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_entries', to='league.player')),
                ('season_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='league.seasonteam')),
            ],
            options={
                'ordering': ['season_team', 'effective_from', 'player'],
                'indexes': [models.Index(fields=['season_team', 'effective_from'], name='league_seas_season__e4c5e2_idx'), models.Index(fields=['player', 'effective_from'], name='league_seas_player__9be31b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='roster_effective_to_gte_from')],
            },
        ),
        migrations.AddConstraint(
            model_name='seasonteam',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='season_team_unique_per_season'),
        ),
        migrations.AddConstraint(
            model_name='seasonteam',
            constraint=models.CheckConstraint(condition=models.Q(('last_week_number__isnull', True), ('last_week_number__gte', models.F('first_week_number')), _connector='OR'), name='season_team_last_week_gte_first'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='season_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('season', 'number'), name='week_unique_number_per_season'),
        ),
        migrations.AddConstraint(
            model_name='scheduledmatch',
            constraint=models.CheckConstraint(condition=models.Q(('table_number__isnull', True), models.Q(('table_number__gte', 1), ('table_number__lte', 5)), _connector='OR'), name='scheduled_match_table_number_range'),
        ),
        migrations.AddConstraint(
            model_name='byeassignment',
            constraint=models.UniqueConstraint(fields=('week', 'season_team'), name='bye_unique_team_per_week'),
        ),
    ]
